### ISSUE TITLE
mathcomp-dev image failures due to opam version mismatch

### ISSUE THREAD

**Issue by palmskog** [math-comp/docker-mathcomp#19]
Since April 1, 2022, I'm seeing CI failures for a bunch of MathComp-related projects using the `mathcomp-dev` Docker image, for example [here for RegLang](https://github.com/coq-community/reglang/runs/5782430599?check_suite_focus=true).

The failure happens during **recompilation** of Coq, which I believe should not be happening in the first place. Specifically, we first see the following version mismatch between opam 2.0 and opam 2.1:
```
$ opam update -y
  This version of opam requires an update to the layout of /home/coq/.opam from version 2.0 to version 2.1, which can't be reverted.
  You may want to back it up before going further.
```
Then, we get the recompilation during a package install:
```
$ opam install -y -j 2 coq-reglang --deps-only
[...]
 The following actions will be performed:
    - recompile ocaml-variants         4.07.1+flambda [upstream or system changes]
[...]
    - recompile coq                    dev*           [uses ocaml]
[...]
```
Finally, Coq compilation fails due to lack of Dune(?):
```
Error:  The compilation of coq.dev failed at "./configure -prefix /home/coq/.opam/4.07.1+flambda -coqide no -native-compiler no".
[...]
Dune could not be found, please ensure you have a working OCaml enviroment
```
This is likely related to the base image upgrade to opam 2.1 (cc: @gares).

**Comment by pi8027** [comment]
IIUC, @erikmd will fix this issue soon: https://github.com/coq-community/docker-base/pull/17#issuecomment-1084946566

**Comment by erikmd** [comment]
Hi @palmskog @pi8027,
Yes, thanks, I'm working on a fix.

To summarize one of the issues that occur:

* Before https://github.com/coq-community/docker-coq/commit/ac47077378e7a019e321745b5f86986d441077e5, `coqorg/coq:dev` FTBFS. So `mathcomp*:coq-dev` was stuck with opam 2.0.
* But `coqorg/base:bare` had already opam 2.1.2.
* As a result, after [this line of `mathcomp-dev`'s Dockerfile](https://github.com/math-comp/math-comp/blob/5cb6f07e0967e9eafea1ab20f219e0af544ec4a9/Dockerfile#L28), we ended up with an (opam binary, opam switch) incompatibility.

**Comment by erikmd** [comment]
Normally, this issue is fixed now. Feel free to reopen otherwise

**Comment by erikmd** [comment]
@palmskog FWIW, the cron worklfow that was part of docker-coq-action's CI had spotted this issue (albeit I hadn't seen the failure e-mail before you opened this :)

- https://github.com/coq-community/docker-coq-action/actions
- https://github.com/coq-community/docker-coq-action/actions/runs/2078458093

Anyway, I'll take this opportunity to add yet another test in that workflow.

**Comment by pi8027** [comment]
I still see this issue [here](https://github.com/coq-community/apery/actions/runs/2159840243) in the following images:
- mathcomp/mathcomp-dev:coq-8.13
- mathcomp/mathcomp-dev:coq-8.14

Recompilation of MathComp happens in some other images (e.g., mathcomp/mathcomp:1.12.0-coq-8.13) too, but for different reasons, it seems.

**Comment by palmskog** [comment]
@erikmd the problem seems to be with `num`:
```
+ (script @ line 12) $ opam install --confirm-level=unsafe-yes -j 2 coq-mathcomp-apery --deps-only
  
  <><> Synchronising pinned packages ><><><><><><><><><><><><><><><><><><><><><><>
  [coq-mathcomp-apery.dev] synchronised (no changes)
  
  The following actions will be performed:
    - install   seq                          base
    - install   conf-perl                    2
    - recompile num                          1.3*            [upstream or system changes]
    - install   re                           1.10.3
    - install   camlp5                       7.14
    - recompile sexplib                      v0.14.0         [uses num]
    - recompile coq                          8.13.2*         [uses num]
```
Is maybe some system package that num uses getting upgraded?

**Comment by erikmd** [comment]
@pi8027 @palmskog Rebuild done:

* https://gitlab.com/coq-community/docker-base/-/pipelines/516226816
* https://gitlab.com/coq-community/docker-coq/-/pipelines/516276310
* https://gitlab.com/math-comp/docker-mathcomp/-/pipelines/516319043
* https://gitlab.com/math-comp/math-comp/-/pipelines/516319272

If a similar issue occurs again (e.g. if you experience a CI slowdown because some pinned packages are recompiled (here, because of a major change in opam-repository; beforehand, because of a bump of the opam binary)), *feel free to open a new issue*.
